/*
 * This file is generated by jOOQ.
 */
package ch.metamodel;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.test_test_uuid_seq</code>
     */
    public static final Sequence<Integer> TEST_TEST_UUID_SEQ = new SequenceImpl<Integer>("test_test_uuid_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
