/*
 * This file is generated by jOOQ.
 */
package ch.metamodel;


import ch.metamodel.tables.FlywaySchemaHistory;
import ch.metamodel.tables.Test;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = ch.metamodel.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.test</code>.
     */
    public static final Test TEST = ch.metamodel.tables.Test.TEST;
}
