/*
 * This file is generated by jOOQ.
 */
package ch.metamodel.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test implements Serializable {

    private static final long serialVersionUID = 995670233;

    private final Integer       testUuid;
    private final LocalDateTime date;

    public Test(Test value) {
        this.testUuid = value.testUuid;
        this.date = value.date;
    }

    public Test(
        Integer       testUuid,
        LocalDateTime date
    ) {
        this.testUuid = testUuid;
        this.date = date;
    }

    public Integer getTestUuid() {
        return this.testUuid;
    }

    public LocalDateTime getDate() {
        return this.date;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Test other = (Test) obj;
        if (testUuid == null) {
            if (other.testUuid != null)
                return false;
        }
        else if (!testUuid.equals(other.testUuid))
            return false;
        if (date == null) {
            if (other.date != null)
                return false;
        }
        else if (!date.equals(other.date))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.testUuid == null) ? 0 : this.testUuid.hashCode());
        result = prime * result + ((this.date == null) ? 0 : this.date.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Test (");

        sb.append(testUuid);
        sb.append(", ").append(date);

        sb.append(")");
        return sb.toString();
    }
}
