/*
 * This file is generated by jOOQ.
 */
package ch.metamodel.tables.daos;


import ch.metamodel.tables.Test;
import ch.metamodel.tables.records.TestRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestDao extends DAOImpl<TestRecord, ch.metamodel.tables.pojos.Test, Integer> {

    /**
     * Create a new TestDao without any configuration
     */
    public TestDao() {
        super(Test.TEST, ch.metamodel.tables.pojos.Test.class);
    }

    /**
     * Create a new TestDao with an attached configuration
     */
    public TestDao(Configuration configuration) {
        super(Test.TEST, ch.metamodel.tables.pojos.Test.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(ch.metamodel.tables.pojos.Test object) {
        return object.getTestUuid();
    }

    /**
     * Fetch records that have <code>test_uuid IN (values)</code>
     */
    public List<ch.metamodel.tables.pojos.Test> fetchByTestUuid(Integer... values) {
        return fetch(Test.TEST.TEST_UUID, values);
    }

    /**
     * Fetch a unique record that has <code>test_uuid = value</code>
     */
    public ch.metamodel.tables.pojos.Test fetchOneByTestUuid(Integer value) {
        return fetchOne(Test.TEST.TEST_UUID, value);
    }

    /**
     * Fetch records that have <code>date IN (values)</code>
     */
    public List<ch.metamodel.tables.pojos.Test> fetchByDate(LocalDateTime... values) {
        return fetch(Test.TEST.DATE, values);
    }
}
